export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const UPDATE_PERSONAL_DATA = 'UPDATE_PERSONAL_DATA';


export const ADD_TRIP_REQUEST = 'ADD_TRIP_REQUEST';
export const ADD_TRIP_SUCCESS = 'ADD_TRIP_SUCCESS';
export const ADD_TRIP_FAILURE = 'ADD_TRIP_FAILURE';

export const UPDATE_TRIP_REQUEST = 'UPDATE_TRIP_REQUEST';
export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS';
export const UPDATE_TRIP_FAILURE = 'UPDATE_TRIP_FAILURE';

export const TRIP_LIST_REQUEST = 'TRIP_LIST_REQUEST';
export const TRIP_LIST_SUCCESS = 'TRIP_LIST_SUCCESS';
export const TRIP_LIST_FAILURE = 'TRIP_LIST_FAILURE';
export const GET_TRIP_LIST_SUCCESS = 'GET_TRIP_LIST_SUCCESS';

export const DOCUMENT_CATEGORY_LIST_REQUEST = 'DOCUMENT_CATEGORY_LIST_REQUEST';
export const DOCUMENT_CATEGORY_LIST_SUCCESS = 'DOCUMENT_CATEGORY_LIST_SUCCESS';
export const DOCUMENT_CATEGORY_LIST_FAILURE = 'DOCUMENT_CATEGORY_LIST_FAILURE';
export const GET_DOCUMENT_CATEGORY_LIST_SUCCESS = 'GET_DOCUMENT_CATEGORY_LIST_SUCCESS';

export const ADD_DOCUMENT_RECORD_REQUEST = 'ADD_DOCUMENT_RECORD_REQUEST';
export const ADD_DOCUMENT_RECORD_SUCCESS = 'ADD_DOCUMENT_RECORD_SUCCESS';
export const ADD_DOCUMENT_RECORD_FAILURE = 'ADD_DOCUMENT_RECORD_FAILURE';

export const RESIDENCY_DOC_LIST_REQUEST = 'RESIDENCY_DOC_LIST_REQUEST';
export const RESIDENCY_DOC_LIST_SUCCESS = 'RESIDENCY_DOC_LIST_SUCCESS';
export const RESIDENCY_DOC_LIST_FAILURE = 'RESIDENCY_DOC_LIST_FAILURE';
export const GET_RESIDENCY_DOC_LIST_SUCCESS = 'GET_RESIDENCY_DOC_LIST_SUCCESS';

export const TRIP_MODE_LIST_REQUEST = 'TRIP_MODE_LIST_REQUEST';
export const TRIP_MODE_LIST_SUCCESS = 'TRIP_MODE_LIST_SUCCESS';
export const TRIP_MODE_LIST_FAILURE = 'TRIP_MODE_LIST_FAILURE';
export const GET_TRIP_MODE_LIST_SUCCESS = 'GET_TRIP_MODE_LIST_SUCCESS';

export const TRIP_TYPE_LIST_FAILURE = 'TRIP_TYPE_LIST_FAILURE';
export const GET_TRIP_TYPE_LIST_SUCCESS = 'GET_TRIP_TYPE_LIST_SUCCESS';

export const GET_TRIP_SUMMARY_DETAILS_SUCCESS = 'GET_TRIP_SUMMARY_DETAILS_SUCCESS';
export const TRIP_SUMMARY_DETAILS_FAILURE = 'TRIP_SUMMARY_DETAILS_FAILURE';

export const GET_TRIP_DETAILS_SUCCESS = 'GET_TRIP_DETAILS_SUCCESS';
export const TRIP_DETAILS_FAILURE = 'TRIP_DETAILS_FAILURE';

export const GET_RESIDENCY_DOC_DETAILS_SUCCESS = 'GET_RESIDENCY_DOC_DETAILS_SUCCESS';
export const RESIDENCY_DOC_DETAILS_FAILURE = 'RESIDENCY_DOC_DETAILS_FAILURE';

export const FINAL_YEAR_PROGRESS_FAILURE = 'FINAL_YEAR_PROGRESS_FAILURE';
export const GET_FINAL_YEAR_PROGRESS_SUCCESS = 'GET_FINAL_YEAR_PROGRESS_SUCCESS';

export const STATE_WISE_RESIDENCY_FAILURE = 'STATE_WISE_RESIDENCY_FAILURE';
export const GET_STATE_WISE_RESIDENCY_SUCCESS = 'GET_STATE_WISE_RESIDENCY_SUCCESS';

export const COMPLIANCE_SCORE_FAILURE = 'COMPLIANCE_SCORE_FAILURE';
export const GET_COMPLIANCE_SCORE_SUCCESS = 'GET_COMPLIANCE_SCORE_SUCCESS';

export const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';

export const STATE_WISE_METRICS_FAILURE = 'STATE_WISE_METRICS_FAILURE';
export const GET_STATE_WISE_METRICS_SUCCESS = 'GET_STATE_WISE_METRICS_SUCCESS';

export const YEAR_WISE_TIMELINE_FAILURE = 'YEAR_WISE_TIMELINE_FAILURE';
export const GET_YEAR_WISE_TIMELINE_SUCCESS = 'GET_YEAR_WISE_TIMELINE_SUCCESS';

export const WEEK_WISE_TIMELINE_FAILURE = 'WEEK_WISE_TIMELINE_FAILURE';
export const GET_WEEK_WISE_TIMELINE_SUCCESS = 'GET_WEEK_WISE_TIMELINE_SUCCESS';

export const MONTH_WISE_TIMELINE_FAILURE = 'MONTH_WISE_TIMELINE_FAILURE';
export const GET_MONTH_WISE_TIMELINE_SUCCESS = 'GET_MONTH_WISE_TIMELINE_SUCCESS';

export const STATE_WISE_TRIPS_FAILURE = 'STATE_WISE_TRIPS_FAILURE';
export const GET_STATE_WISE_TRIPS_SUCCESS = 'GET_STATE_WISE_TRIPS_SUCCESS';

export const UPDATE_STATE_THRESHOLD_REQUEST = 'UPDATE_STATE_THRESHOLD_REQUEST';
export const UPDATE_STATE_THRESHOLD_SUCCESS = 'UPDATE_STATE_THRESHOLD_SUCCESS';
export const UPDATE_STATE_THRESHOLD_FAILURE = 'UPDATE_STATE_THRESHOLD_FAILURE';

export const TYPE_OF_DAY_LIST_REQUEST = 'TYPE_OF_DAY_LIST_REQUEST';
export const TYPE_OF_DAY_LIST_FAILURE = 'TYPE_OF_DAY_LIST_FAILURE';
export const GET_TYPE_OF_DAY_LIST_SUCCESS = 'GET_TYPE_OF_DAY_LIST_SUCCESS'

export const STATES_LIST_REQUEST = 'STATES_LIST_REQUEST';
export const STATES_LIST_FAILURE = 'STATES_LIST_FAILURE';
export const GET_STATES_LIST_SUCCESS = 'GET_STATES_LIST_SUCCESS'

export const ADD_MISSINGDAY_REQUEST = 'ADD_MISSINGDAY_REQUEST';
export const ADD_MISSINGDAY_SUCCESS = 'ADD_MISSINGDAY_SUCCESS';
export const ADD_MISSINGDAY_FAILURE = 'ADD_MISSINGDAY_FAILURE';

export const MISSING_ACTIVITY_LIST_REQUEST = 'MISSING_ACTIVITY_LIST_REQUEST';
export const MISSING_ACTIVITY_LIST_FAILURE = 'MISSING_ACTIVITY_LIST_FAILURE';
export const GET_MISSING_ACTIVITY_LIST_SUCCESS = 'GET_MISSING_ACTIVITY_LIST_SUCCESS';

export const UPDATE_MISSINGDAY_REQUEST = 'UPDATE_MISSINGDAY_REQUEST';
export const UPDATE_MISSINGDAY_SUCCESS = 'UPDATE_MISSINGDAY_SUCCESS';
export const UPDATE_MISSINGDAY_FAILURE = 'UPDATE_MISSINGDAY_FAILURE';

export const REPORTS_REQUEST = 'REPORTS_REQUEST';
export const REPORTS_FAILURE = 'REPORTS_FAILURE';
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS'

export const FAQS_REQUEST = 'FAQS_REQUEST';
export const FAQS_FAILURE = 'FAQS_FAILURE';
export const GET_FAQS_SUCCESS = 'GET_FAQS_SUCCESS'

export const SUPPORT_CONTACT_REQUEST = 'SUPPORT_CONTACT_REQUEST';
export const SUPPORT_CONTACT_FAILURE = 'SUPPORT_CONTACT_FAILURE';
export const GET_SUPPORT_CONTACT_SUCCESS = 'GET_SUPPORT_CONTACT_SUCCESS'

export const ABOUT_APP_REQUEST = 'ABOUT_APP_REQUEST';
export const ABOUT_APP_FAILURE = 'ABOUT_APP_FAILURE';
export const GET_ABOUT_APP_SUCCESS = 'GET_ABOUT_APP_SUCCESS'

export const PRIVACY_POLICY_REQUEST = 'PRIVACY_POLICY_REQUEST';
export const PRIVACY_POLICY_FAILURE = 'PRIVACY_POLICY_FAILURE';
export const GET_PRIVACY_POLICY_SUCCESS = 'GET_PRIVACY_POLICY_SUCCESS'

export const SET_APP_LANGUAGE = 'SET_APP_LANGUAGE'

// Subscription
export const SET_SUBSCRIPTION_PLAN = 'SET_SUBSCRIPTION_PLAN';
export const SET_SUBSCRIPTION_LOADING = 'SET_SUBSCRIPTION_LOADING';
export const SET_SUBSCRIPTION_ERROR = 'SET_SUBSCRIPTION_ERROR';
export const CLEAR_SUBSCRIPTION = 'CLEAR_SUBSCRIPTION';
export const SET_SUBSCRIPTION_PRODUCTS = 'SET_SUBSCRIPTION_PRODUCTS';
export const SET_TRIAL_START = 'SET_TRIAL_START';