export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const UPDATE_PERSONAL_DATA = 'UPDATE_PERSONAL_DATA';


export const ADD_TRIP_REQUEST = 'ADD_TRIP_REQUEST';
export const ADD_TRIP_SUCCESS = 'ADD_TRIP_SUCCESS';
export const ADD_TRIP_FAILURE = 'ADD_TRIP_FAILURE';

export const UPDATE_TRIP_REQUEST = 'UPDATE_TRIP_REQUEST';
export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS';
export const UPDATE_TRIP_FAILURE = 'UPDATE_TRIP_FAILURE';

export const TRIP_LIST_REQUEST = 'TRIP_LIST_REQUEST';
export const TRIP_LIST_SUCCESS = 'TRIP_LIST_SUCCESS';
export const TRIP_LIST_FAILURE = 'TRIP_LIST_FAILURE';
export const GET_TRIP_LIST_SUCCESS = 'GET_TRIP_LIST_SUCCESS';

export const DOCUMENT_CATEGORY_LIST_REQUEST = 'DOCUMENT_CATEGORY_LIST_REQUEST';
export const DOCUMENT_CATEGORY_LIST_SUCCESS = 'DOCUMENT_CATEGORY_LIST_SUCCESS';
export const DOCUMENT_CATEGORY_LIST_FAILURE = 'DOCUMENT_CATEGORY_LIST_FAILURE';
export const GET_DOCUMENT_CATEGORY_LIST_SUCCESS = 'GET_DOCUMENT_CATEGORY_LIST_SUCCESS';

export const ADD_DOCUMENT_RECORD_REQUEST = 'ADD_DOCUMENT_RECORD_REQUEST';
export const ADD_DOCUMENT_RECORD_SUCCESS = 'ADD_DOCUMENT_RECORD_SUCCESS';
export const ADD_DOCUMENT_RECORD_FAILURE = 'ADD_DOCUMENT_RECORD_FAILURE';

export const RESIDENCY_DOC_LIST_REQUEST = 'RESIDENCY_DOC_LIST_REQUEST';
export const RESIDENCY_DOC_LIST_SUCCESS = 'RESIDENCY_DOC_LIST_SUCCESS';
export const RESIDENCY_DOC_LIST_FAILURE = 'RESIDENCY_DOC_LIST_FAILURE';
export const GET_RESIDENCY_DOC_LIST_SUCCESS = 'GET_RESIDENCY_DOC_LIST_SUCCESS';

export const TRIP_MODE_LIST_REQUEST = 'TRIP_MODE_LIST_REQUEST';
export const TRIP_MODE_LIST_SUCCESS = 'TRIP_MODE_LIST_SUCCESS';
export const TRIP_MODE_LIST_FAILURE = 'TRIP_MODE_LIST_FAILURE';
export const GET_TRIP_MODE_LIST_SUCCESS = 'GET_TRIP_MODE_LIST_SUCCESS';

export const TRIP_TYPE_LIST_FAILURE = 'TRIP_TYPE_LIST_FAILURE';
export const GET_TRIP_TYPE_LIST_SUCCESS = 'GET_TRIP_TYPE_LIST_SUCCESS';

export const GET_TRIP_SUMMARY_DETAILS_SUCCESS = 'GET_TRIP_SUMMARY_DETAILS_SUCCESS';
export const TRIP_SUMMARY_DETAILS_FAILURE = 'TRIP_SUMMARY_DETAILS_FAILURE';

export const GET_TRIP_DETAILS_SUCCESS = 'GET_TRIP_DETAILS_SUCCESS';
export const TRIP_DETAILS_FAILURE = 'TRIP_DETAILS_FAILURE';

export const GET_RESIDENCY_DOC_DETAILS_SUCCESS = 'GET_RESIDENCY_DOC_DETAILS_SUCCESS';
export const RESIDENCY_DOC_DETAILS_FAILURE = 'RESIDENCY_DOC_DETAILS_FAILURE';

export const FINAL_YEAR_PROGRESS_FAILURE = 'FINAL_YEAR_PROGRESS_FAILURE';
export const GET_FINAL_YEAR_PROGRESS_SUCCESS = 'GET_FINAL_YEAR_PROGRESS_SUCCESS';


export const SET_APP_LANGUAGE = 'SET_APP_LANGUAGE'